import {assetUrl} from './asset-url';
import StudyTools from './study-tools';
import {useViewHistory} from './use-view-history';
import {readViewUrl,viewUrl,partVisible} from './viewer-state';
import {iframeCode} from './embed';
import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Copy,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={focus:0,contextOpacity:1,region:'all',peel:0,hidden:[],labels:true,explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const embedded=new URLSearchParams(location.search).get('embed')==='1';
 const [model,setModel]=useState<'male-full'|'male-detail'|'male'|'female'>(()=>{const m=new URLSearchParams(location.search).get('model');return m==='male-full'||m==='male'||m==='female'?m:'male-detail';});
 const sex=model==='female'?'female':'male';
 const [atlas,setAtlas]=useState<Atlas|null>(null),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'study'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const cameraRef=useRef<number[]|undefined>(undefined),pendingUrl=useRef(location.search);
 const {state,setState,loadState,undo,redo,canUndo,canRedo}=useViewHistory(initial,()=>cameraRef.current);
 const [addSelection,setAddSelection]=useState(false),[shareLink,setShareLink]=useState(''),[copyStatus,setCopyStatus]=useState('');
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setPanel(null);setQuery('');cameraRef.current=undefined;fetch(assetUrl(model==='male-full'?'/models/atlas-male-full.json':model==='male-detail'?'/models/atlas-male-detail.json':sex==='female'?'/models/atlas-female.json':'/models/atlas.json'),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>{setAtlas(data as Atlas);const base:SceneState={...initial,skinOpacity:model==='male-full'?1:.1,visible:sex==='female'||model==='male-full'?[...DEFAULT_VISIBLE,'integumentary']:DEFAULT_VISIBLE};loadState(pendingUrl.current?readViewUrl(pendingUrl.current,data as Atlas,base):base);pendingUrl.current='';}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[model]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{const pop=()=>{pendingUrl.current=location.search;const m=new URLSearchParams(location.search).get('model');const next=m==='male-full'||m==='male'||m==='female'?m:'male-detail';if(next!==model)setModel(next);else if(atlas){loadState(readViewUrl(location.search,atlas,initial));pendingUrl.current='';}};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[model,atlas,loadState]);
 const currentViewUrl=()=>viewUrl(location.href,model,state,cameraRef.current??state.camera);
 const share=()=>{const url=currentViewUrl();history.replaceState(null,'',url);setShareLink(url);setCopyStatus('');void navigator.clipboard?.writeText(url).then(()=>setCopyStatus('Link copied')).catch(()=>{});};
 const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);setCopyStatus(`${label} copied`);}catch{setCopyStatus('Select the text above to copy it.');}};
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const currentChoice=selectedParts.length===1?{id:selected!.conceptId,name:selected!.name,elements:state.selected}:chosen&&chosen.elements.length===state.selected.length&&chosen.elements.every(id=>state.selected.includes(id))?chosen:{id:'selection-set',name:`${state.selected.length} selected pieces`,elements:state.selected};
 const visibleCount=atlas?.parts.filter(p=>partVisible(p,state)&&(state.selected.includes(p.id)||(!state.selected.length||(state.contextOpacity??1)>0)&&(p.system!=='integumentary'||(state.skinOpacity??.1)>0))).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:addSelection?[...new Set([...s.selected,...c.elements])]:c.elements,isolate:false,contextOpacity:s.contextOpacity===1?.18:s.contextOpacity,rotate:false,camera:undefined}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas,addSelection]);
 const choosePart=(id:string,add=false)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:add||addSelection?[...new Set([...s.selected,id])]:[id],isolate:false,contextOpacity:s.contextOpacity===1?.18:s.contextOpacity,rotate:false,camera:undefined}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,skinOpacity:model==='male-full'?1:.1,visible:sex==='female'||model==='male-full'?[...DEFAULT_VISIBLE,'integumentary']:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search'|'study')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className={`studio ${embedded?'embedded':''}`}>
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:(details&&selectedParts.length>0)||panel==='study'}} onSelect={choosePart} onCamera={camera=>{cameraRef.current=camera;}} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="anatomy-choice"><Select value={model} onValueChange={value=>{if(value==='male-full'||value==='male-detail'||value==='male'||value==='female')setModel(value);}} items={[{value:'male-full',label:'Male · full resolution + skin'},{value:'male-detail',label:'Male · detailed'},{value:'male',label:'Male · standard'},{value:'female',label:'Female anatomy'}]}><SelectTrigger aria-label="Choose anatomy model"><SelectValue/></SelectTrigger><SelectContent className="anatomy-choice-menu"><SelectItem value="male-full">Male · full resolution + skin</SelectItem><SelectItem value="male-detail">Male · detailed</SelectItem><SelectItem value="male">Male · standard</SelectItem><SelectItem value="female">Female anatomy</SelectItem></SelectContent></Select></div><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'…'} m{sex==='female'&&<button className="coverage-link" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Partial coverage</button>}</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" aria-label="Open study tools" onClick={()=>openPanel('study')}><Layers3 size={18}/><span>Study</span></Button>{embedded?<a className="open-full" href={currentViewUrl()} onClick={e=>{e.currentTarget.href=currentViewUrl();}} target="_blank" rel="noopener noreferrer" aria-label="Open full Human Atlas viewer" title="Open full viewer"><ArrowUpRight size={18}/></a>:<Button variant="ghost" className="icon-button" aria-label="Share and embed this view" onClick={share}><ArrowUpRight size={18}/></Button>}</nav>
  {panel==='study'&&atlas&&<StudyTools atlas={atlas} state={state} setState={setState} close={()=>setPanel(null)} undo={undo} redo={redo} canUndo={canUndo} canRedo={canRedo} add={addSelection} setAdd={setAddSelection} search={()=>{setAddSelection(true);setPanel('search');}}/>}
  {shareLink&&<div className="share-view glass" role="dialog" aria-label="Share and embed view"><div className="panel-heading"><span>Share this view</span><Button variant="ghost" className="icon-button" onClick={()=>setShareLink('')} aria-label="Close share options"><X size={18}/></Button></div><label>View URL<input aria-label="View URL" readOnly value={shareLink} onFocus={e=>e.target.select()}/></label><Button variant="outline" onClick={()=>void copy(shareLink,'Link')}><Copy size={15}/> Copy link</Button><label>Embed on a website<textarea aria-label="Iframe embed code" readOnly rows={3} value={iframeCode(shareLink)} onFocus={e=>e.target.select()}/></label><Button variant="outline" onClick={()=>void copy(iframeCode(shareLink),'Embed code')}><Copy size={15}/> Copy embed code</Button><p>Embeds this model, camera, selection and layers. Adjust the iframe height to fit your page.</p><p role="status">{copyStatus}</p></div>}
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''} ${panel==='study'?'study-hidden':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.filter(x=>!['pregnancy','attachments','regions','schematic'].includes(x.id)).every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,isolate:false,visible:activeSystems.map(x=>x.id).filter(x=>!['pregnancy','attachments','regions','schematic'].includes(x))}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,isolate:false,visible:['skeletal']}))}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Organs</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   {counts.integumentary>0&&<div className="skin-control"><label id="skin-label">Skin / body surface <output>{state.visible.includes('integumentary')?Math.round((state.skinOpacity??.1)*100):0}%</output></label><Slider aria-labelledby="skin-label" min={0} max={100} step={5} value={[state.visible.includes('integumentary')?(state.skinOpacity??.1)*100:0]} onValueChange={v=>{const opacity=(Array.isArray(v)?v[0]:v)/100;setState(s=>({...s,skinOpacity:opacity,visible:opacity>0?[...s.visible.filter(x=>x!=='integumentary'),'integumentary']:s.visible.filter(x=>x!=='integumentary')}));}}/><p>Outer surface reference; not separate skin layers.</p></div>}<div className="panel-foot"><span>{visibleCount.toLocaleString()} m visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><label className="check-label selection-mode"><input type="checkbox" checked={addSelection} onChange={e=>setAddSelection(e.target.checked)}/>Add to selection set</label><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false,camera:undefined}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(currentChoice?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':sex==='female'?'FEMALE · REFERENCE ANATOMY':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'…'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{currentChoice.name}</SheetTitle></div><div className="detail-scroll" key={`${currentChoice?.id}-${state.isolate}`}><SheetDescription className="structure-description">{currentChoice&&selected?(sex==='female'&&selected.system==='reproductive'&&!EXPLANATIONS[currentChoice.name.toLowerCase()]?'Female reproductive structures include the ovaries, uterine tubes, uterus, cervix, and vagina. Together they support oocyte development, fertilization, menstruation, and pregnancy.':explanation(currentChoice.name,selected.system)):''}</SheetDescription>{currentChoice&&!EXPLANATIONS[currentChoice.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{currentChoice?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}</div>}</div><div className="detail-actions"><Button variant="outline" onClick={()=>setState(s=>({...s,focus:(s.focus??0)+1,camera:undefined}))}>Focus selection</Button><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">MODEL COVERAGE</div><SheetTitle className="structure-title">About this anatomy</SheetTitle><SheetDescription>Explore male and female reference models with different levels of detail.</SheetDescription><div className="about-copy"><p><strong>Male · detailed</strong><br/>4,391 selectable pieces, including upper limbs, nerves, muscles, ligaments, and attachment markers. Some structures are mirrored. Schematic, fascia, region, and attachment layers are hidden by default.</p><p><strong>Male · standard</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference.</p><p><strong>Female anatomy</strong><br/>1,038 selectable pieces and 1,253 named concepts, including 90 muscle pieces. Upper-body muscles, skull, ribs, shoulder, arm, hand, and foot bones are still missing. Eight pregnancy reference pieces are in a separate layer, hidden by default.</p><p>These models have different coverage. Neither contains every human structure or variation. Named concepts can contain multiple pieces; each mesh is rendered once.</p><p>Colors and system groupings are designed for exploration. The full-resolution male option preserves mesh detail; the other options simplify geometry for the web. Short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p></div></SheetContent></Sheet>
 </main>;
}
