import {assetUrl} from './asset-url';
import StudyTools from './study-tools';
import {useViewHistory} from './use-view-history';
import {readViewUrl,viewUrl} from './viewer-state';
import {readEmbedUi,type EmbedUi} from './embed';
import ShareView from './share-view';
import SelectionInspector from './selection-inspector';
import SystemTree,{type Hierarchy} from './system-tree';
import DepthTree from './depth-tree';
import {DEPTH_LAYERS} from './depth-layers';
import {flushSync} from 'react-dom';
import {registerAtlasTools,type AgentActions,type AgentViewChange} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,BookmarkPlus,Download,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {CELL_VISIBLE,DEFAULT_VISIBLE,SYSTEMS,structureName,type Atlas,type Concept,type SceneState,type View} from './anatomy';
const initial:SceneState={focus:0,contextOpacity:1,region:'all',peel:0,depthHidden:[],hidden:[],labels:true,explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
type Model='male-full'|'male-detail'|'male'|'female'|'embryo'|'cell'|'local-male'|'local-female';
const modelChoices:{value:Model;label:string}[]=[
 {value:'male-full',label:'Male · full resolution + skin'},
 {value:'male-detail',label:'Male · detailed'},
 {value:'male',label:'Male · standard'},
 {value:'female',label:'Female · partial'},
 {value:'embryo',label:'Embryo · partial'},
 {value:'cell',label:'Human eukaryotic cell'},
 ...(import.meta.env.DEV?[{value:'local-male' as const,label:'Male · local Zygote'},{value:'local-female' as const,label:'Female · local Zygote'}]:[]),
];
const parseModel=(value:string|null):Model=>modelChoices.find(choice=>choice.value===value)?.value??'male-detail';
const cataloguePath=(model:Model)=>model==='local-male'?'/local-models/male.json':model==='local-female'?'/local-models/female.json':model==='male-full'||model==='male-detail'?'/models/atlas-male-complete.json':model==='female'?'/models/atlas-hra-female.json':model==='embryo'?'/models/atlas-embryo.json':model==='cell'?'/models/atlas-cell.json':'/models/atlas.json';
const defaultLayers=(model:Model,sex:'male'|'female')=>model==='embryo'?['pregnancy' as const]:model==='cell'?CELL_VISIBLE:sex==='female'||model==='male-full'||model.startsWith('local-')?[...DEFAULT_VISIBLE,'integumentary' as const]:DEFAULT_VISIBLE;
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const framed=window.self!==window.top;
 const [compactFrame,setCompactFrame]=useState(()=>framed&&(window.innerWidth<768||window.innerHeight<600));
 useEffect(()=>{if(!framed)return;const update=()=>setCompactFrame(window.innerWidth<768||window.innerHeight<600);window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update);},[framed]);
 const embedParams=new URLSearchParams(location.search);
 const embedded=embedParams.get('embed')==='1'||compactFrame;
 const embedUi=embedded?readEmbedUi(location.search):null;
 const requestedUi=embedParams.get('ui')?.split(',')??[];
 const show=(control:EmbedUi)=>{
  if(control==='camera')return requestedUi.includes('camera')&&(!embedded||!!embedUi?.has('camera'));
  if(compactFrame&&control==='explode')return requestedUi.includes(control);
  return !embedded||!!embedUi?.has(control);
 };
 const [model,setModel]=useState<Model>(()=>parseModel(new URLSearchParams(location.search).get('model')));
 const [hierarchy,setHierarchy]=useState<Hierarchy|'depth'>(()=>{const tree=new URLSearchParams(location.search).get('tree');return tree==='regions'||tree==='depth'&&model!=='cell'?tree:'systems';});
 const [explodeSteps,setExplodeSteps]=useState(7),[layersVisible,setLayersVisible]=useState(true);
 const sex=model==='female'||model==='embryo'||model==='local-female'?'female':'male';
 const [atlas,setAtlas]=useState<Atlas|null>(null),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'study'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const cameraRef=useRef<number[]|undefined>(undefined),captureRef=useRef<(()=>Promise<Blob>)|null>(null),pendingUrl=useRef(location.search);
 const agentActionsRef=useRef<AgentActions|null>(null);
 const agentInspectRef=useRef<(concept:Concept)=>void>(()=>{});
 const {state,setState,loadState,undo,redo,canUndo,canRedo}=useViewHistory(initial,()=>cameraRef.current);
 const [addSelection,setAddSelection]=useState(false),[shareLink,setShareLink]=useState(''),[exportStatus,setExportStatus]=useState('');
 const [covering,setCovering]=useState<string[]>([]),[allowFadedSelection,setAllowFadedSelection]=useState(false);
 const peelBaseline=useRef<string[]>([]);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setPanel(null);setQuery('');cameraRef.current=undefined;fetch(assetUrl(cataloguePath(model)),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error(model.startsWith('local-')?'Local models are missing. Run npm run import:local-models.':'The anatomy catalogue could not be loaded.');return r.json();}).then(data=>{setAtlas(data as Atlas);const base:SceneState={...initial,skinOpacity:model==='cell'?.18:model==='male-full'?1:model.startsWith('local-')?0:.1,visible:defaultLayers(model,sex)};const restored=pendingUrl.current?readViewUrl(pendingUrl.current,data as Atlas,base):base;const terms=new URLSearchParams(pendingUrl.current).getAll('select');setChosen(terms.length===1?(data as Atlas).concepts.find(concept=>concept.id===terms[0])??null:null);loadState(restored);setDetails(restored.selected.length>0);pendingUrl.current='';}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[model]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{const pop=()=>{pendingUrl.current=location.search;const params=new URLSearchParams(location.search),next=parseModel(params.get('model')),tree=params.get('tree');setHierarchy(tree==='regions'||tree==='depth'&&next!=='cell'?tree:'systems');if(next!==model)setModel(next);else if(atlas){const terms=params.getAll('select'),restored=readViewUrl(location.search,atlas,initial);setChosen(terms.length===1?atlas.concepts.find(concept=>concept.id===terms[0])??null:null);loadState(restored);setDetails(restored.selected.length>0);pendingUrl.current='';}};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[model,atlas,loadState]);
 const currentViewUrl=()=>{const url=new URL(viewUrl(location.href,model,state,cameraRef.current??state.camera));if(hierarchy!=='systems')url.searchParams.set('tree',hierarchy);if(embedParams.has('ui'))url.searchParams.set('ui',embedParams.get('ui')!);return url.href;};
 const share=()=>{const url=currentViewUrl();history.replaceState(null,'',url);setShareLink(url);};
 const downloadPng=async()=>{try{setExportStatus('Preparing PNG…');const blob=await captureRef.current?.();if(!blob)throw new Error('The 3D view is still loading.');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`human-atlas-${model}-${Date.now()}.png`;document.body.appendChild(link);link.click();link.remove();setExportStatus('PNG download started.');setTimeout(()=>{URL.revokeObjectURL(url);setExportStatus('');},60_000);return {ok:true};}catch(error){const message=error instanceof Error?error.message:'Could not export the image.';setExportStatus(message);return {ok:false,error:message};}};
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0];
 const currentChoice=chosen&&chosen.elements.length===state.selected.length&&chosen.elements.every(id=>state.selected.includes(id))?chosen:selectedParts.length===1?{id:selected!.conceptId,name:selected!.name,elements:state.selected}:{id:'selection-set',name:`${state.selected.length} selected pieces`,elements:state.selected};
 const selectionKey=state.selected.join('|');
 useEffect(()=>{peelBaseline.current=state.hidden??[];setCovering([]);},[selectionKey]);
 const peelDepth=covering.filter(id=>(state.hidden??[]).includes(id)).length;
 const restoreInspectionHidden=(hidden:string[]|undefined)=>{const peeled=new Set(covering.filter(id=>!peelBaseline.current.includes(id)));return (hidden??[]).filter(id=>!peeled.has(id));};
 const setPeelDepth=(depth:number)=>setState(s=>({...s,hidden:[...new Set([...restoreInspectionHidden(s.hidden),...covering.slice(0,depth)])]}));
 const clearSelection=()=>{setState(s=>({...s,hidden:restoreInspectionHidden(s.hidden),selected:[],isolate:false,camera:cameraRef.current??s.camera}));setChosen(null);setDetails(false);setCovering([]);};
 const hideSelection=()=>{setState(s=>({...s,hidden:[...new Set([...restoreInspectionHidden(s.hidden),...s.selected])],selected:[],isolate:false,camera:cameraRef.current??s.camera}));setChosen(null);setDetails(false);setCovering([]);};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.key!=='Delete'&&e.key!=='Backspace')||e.defaultPrevented||e.metaKey||e.ctrlKey||e.altKey||!state.selected.length)return;const target=e.target;if(target instanceof HTMLElement&&(target.isContentEditable||target.closest('input, textarea, select, [role="textbox"]')))return;e.preventDefault();hideSelection();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[state.selected.length,covering]);
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,hidden:restoreInspectionHidden(s.hidden),selected:addSelection?[...new Set([...s.selected,...c.elements])]:c.elements,isolate:false,contextOpacity:s.contextOpacity===1?.18:s.contextOpacity,rotate:false,camera:undefined}));setDetails(true);setPanel(null);};
 agentInspectRef.current=choose;
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>agentInspectRef.current(c)),{
  snapshot:()=>agentActionsRef.current?.snapshot(),update:change=>agentActionsRef.current?.update(change),command:action=>agentActionsRef.current?.command(action),url:()=>agentActionsRef.current?.url()??location.href,
 });},[atlas]);
 const choosePart=(id:string,add=false)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:structureName(p.name),elements:[id]});setState(s=>({...s,hidden:restoreInspectionHidden(s.hidden),selected:add||addSelection?[...new Set([...s.selected,id])]:[id],isolate:false,contextOpacity:s.contextOpacity===1?.18:s.contextOpacity,rotate:false,camera:undefined}));setDetails(true);setPanel(null);};
 const reset=()=>{setState(s=>({...initial,skinOpacity:model==='cell'?.18:model==='male-full'?1:model.startsWith('local-')?0:.1,visible:defaultLayers(model,sex),reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search'|'study')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const toggleLayers=()=>{if(window.innerWidth<768||window.innerHeight<=600){openPanel('layers');return;}setDetails(false);setPanel(null);setLayersVisible(value=>!value);setState(s=>({...s,reset:s.reset+1}));};
 const setExplosion=(value:number,magnetic=false)=>{const interval=100/Math.max(1,explodeSteps),nearest=Math.round(value/interval)*interval,adjusted=magnetic&&Math.abs(value-nearest)<=Math.min(4,interval*.28)?nearest:value;setState(s=>({...s,explode:adjusted/100,rotate:false,camera:undefined}));};
 const resolveAgentPieces=(terms:string[])=>[...new Set(terms.flatMap(term=>{const part=atlas?.parts.find(p=>p.id===term||p.sourceId===term);if(part)return [part.id];const matches=atlas?.concepts.filter(c=>c.id===term||c.name.toLowerCase()===term.toLowerCase())??[];if(!matches.length)throw new Error(`No structure matches "${term}" in this model.`);return matches.flatMap(c=>c.elements);} ))];
 agentActionsRef.current={
  snapshot:()=>({model,hierarchy,selected:state.selected,systems:state.visible,availableSystems:Object.entries(counts).filter(([,count])=>count>0).map(([id,count])=>({id,pieces:count})),depthHidden:state.depthHidden??[],availableDepthLayers:model==='cell'?[]:DEPTH_LAYERS,hidden:state.hidden??[],view:state.view,region:state.region??'all',context:state.contextOpacity??1,skinOpacity:state.skinOpacity??.1,explode:state.explode,labels:state.labels!==false,isolate:state.isolate,rotate:state.rotate,section:state.section??null,camera:cameraRef.current??state.camera??null,url:currentViewUrl()}),
  url:currentViewUrl,
  update:(change:AgentViewChange)=>{
   if(change.model&&change.model!==model){if(!modelChoices.some(choice=>choice.value===change.model))throw new Error('Unknown model.');setModel(change.model as Model);setHierarchy('systems');return {model:change.model,loading:true};}
   const selected=change.structures===undefined?undefined:resolveAgentPieces(change.structures),hidden=change.hidden===undefined?undefined:resolveAgentPieces(change.hidden);
   if(change.isolate===true&&!(selected??state.selected).length)throw new Error('Isolation requires a selected structure.');
   if(change.rotate===true&&(change.explode??state.explode)>.04)throw new Error('Auto rotation is available only when the model is assembled.');
   if(change.isolate===true&&change.explode!==undefined&&change.explode>0)throw new Error('Isolation and Explode cannot be active together.');
   if(change.hierarchy)setHierarchy(change.hierarchy);
   if(selected){setChosen(null);setDetails(selected.length>0);setCovering([]);}
   setState(s=>({...s,...(selected?{selected}:{}),...(hidden?{hidden}:{}),...(change.systems?{visible:change.systems as SceneState['visible']}:{}),...(change.depthHidden?{depthHidden:change.depthHidden}:{}),...(change.view?{view:change.view as View}:{}),...(change.region?{region:change.region}:{}),...(change.context!==undefined?{contextOpacity:change.context}:selected?.length&&s.contextOpacity===1?{contextOpacity:.18}:{}),...(change.skinOpacity!==undefined?{skinOpacity:change.skinOpacity}:{}),...(change.explode!==undefined?{explode:change.explode,rotate:change.explode>.04?false:s.rotate}:{}),...(change.labels!==undefined?{labels:change.labels}:{}),...(change.isolate!==undefined?{isolate:change.isolate,explode:change.isolate?0:s.explode}:selected?.length===0?{isolate:false}:{}),...(change.rotate!==undefined?{rotate:change.rotate}:{}),...(change.section!==undefined?{section:change.section?{enabled:true,...change.section}:{enabled:false,axis:'axial' as const,position:.5,flip:false}}:{}),...(change.camera?{camera:change.camera}:{}),...(change.focus?{focus:(s.focus??0)+1}:{}),...((change.view||change.region)?{reset:s.reset+1}:{} )}));
   return {updated:true,...change};
  },
  command:async action=>{switch(action){case 'undo':undo();break;case 'redo':redo();break;case 'reset':reset();break;case 'focus':setState(s=>({...s,focus:(s.focus??0)+1,camera:undefined}));break;case 'hide-selection':hideSelection();break;case 'clear-selection':clearSelection();break;case 'download-png':return downloadPng();default:throw new Error('Unknown viewer action.');}return {action,done:true};},
 };
 return <main className={`studio ${embedded?'embedded':''}`}>
  {atlas&&<AnatomyScene atlas={atlas} hierarchy={hierarchy} state={{...state,inspectorOpen:(show('details')&&details&&selectedParts.length>0)||(show('study')&&panel==='study')}} onSelect={choosePart} onCamera={camera=>{cameraRef.current=camera;}} onCovering={ids=>setCovering(current=>current.some(id=>(state.hidden??[]).includes(id))?current:ids.filter(id=>!peelBaseline.current.includes(id)))} onExplosionSteps={steps=>setExplodeSteps(current=>current===steps?current:steps)} allowFadedSelection={allowFadedSelection} onCapture={capture=>{captureRef.current=capture;}} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
 {(show('model')||show('explode'))&&<header className="identity"><div className="anatomy-choice">{show('model')&&<Select value={model} onValueChange={(value:string|null)=>{if(value==='about'){setDetails(false);setPanel(null);setAbout(true);}else if(modelChoices.some(choice=>choice.value===value)){setModel(value as Model);setHierarchy('systems');}}} items={[...modelChoices,{value:'about',label:'About model coverage'}]}><SelectTrigger aria-label="Choose anatomy model"><SelectValue>{modelChoices.find(choice=>choice.value===model)?.label} · {atlas?atlas.parts.length.toLocaleString():'…'}</SelectValue></SelectTrigger><SelectContent className="anatomy-choice-menu">{modelChoices.map(choice=><SelectItem key={choice.value} value={choice.value}>{choice.label}</SelectItem>)}<SelectItem value="about">About model coverage</SelectItem></SelectContent></Select>}{show('systems')&&<button type="button" className="model-action" aria-label="Layers" title="Layers" aria-controls="anatomy-browser" aria-expanded={window.innerWidth<768||window.innerHeight<=600?panel==='layers':layersVisible} onClick={toggleLayers}><Layers3 size={17}/></button>}<button type="button" className="model-action" aria-label="Assemble and reset" title="Reset" onClick={reset}><RotateCcw size={17}/></button></div></header>}
  {(!embedded||['search','study','systems','open','download'].some(id=>embedUi?.has(id as EmbedUi)))&&<nav className="top-actions" aria-label="Explorer panels">{show('search')&&<Button variant="ghost" className={`icon-button ${panel==='search'?'active':''}`} onClick={()=>openPanel('search')} aria-label="Find a structure" title="Find a structure"><Search size={18}/></Button>}{show('study')&&<Button variant="ghost" className="icon-button" aria-label="Study tools" title="Study tools" onClick={()=>openPanel('study')}><Info size={18}/></Button>}{embedded&&show('systems')&&!show('model')&&<Button variant="ghost" className="icon-button" aria-label="Layers" title="Layers" onClick={()=>openPanel('layers')}><Layers3 size={18}/></Button>}{embedded&&show('open')&&<a className="open-full" href={currentViewUrl()} onClick={e=>{e.currentTarget.href=currentViewUrl();}} target="_blank" rel="noopener noreferrer" aria-label="Open full Human Atlas viewer" title="Open full viewer"><ArrowUpRight size={18}/></a>}{!embedded&&<Button variant="ghost" className="icon-button" aria-label="Save or open views" title="Save or open views" disabled={!atlas||progress<100} onClick={share}><BookmarkPlus size={18}/></Button>}{show('download')&&<Button variant="ghost" className="icon-button" aria-label="Download PNG of 3D view" title="Download PNG" onClick={()=>void downloadPng()}><Download size={18}/></Button>}</nav>}
  {exportStatus&&<p className="export-status glass" role="status">{exportStatus}</p>}
  {panel==='study'&&atlas&&show('study')&&<StudyTools atlas={atlas} state={state} setState={setState} close={()=>setPanel(null)} undo={undo} redo={redo} canUndo={canUndo} canRedo={canRedo} add={addSelection} setAdd={setAddSelection} search={()=>{setAddSelection(true);setPanel('search');}}/>}
  {shareLink&&<ShareView viewUrl={shareLink} defaultName={state.selected.length?structureName(currentChoice.name):model==='cell'?'Human cell view':`${sex==='female'?'Female':'Male'} anatomy view`} close={()=>setShareLink('')}/>}
  {show('systems')&&<section id="anatomy-browser" className={`layers-panel glass ${panel==='layers'?'mobile-open':''} ${panel==='study'?'study-hidden':''} ${layersVisible?'':'is-hidden'}`} aria-label={model==='cell'?'Cell browser':'Anatomy browser'}>
   <div className="hierarchy-header"><div className="hierarchy-tabs" role="tablist" aria-label="Browse anatomy by"><button type="button" role="tab" aria-selected={hierarchy==='systems'} className={hierarchy==='systems'?'active':''} onClick={()=>setHierarchy('systems')}>{model==='cell'?'Functions':'Systems'}</button><button type="button" role="tab" aria-selected={hierarchy==='regions'} className={hierarchy==='regions'?'active':''} onClick={()=>setHierarchy('regions')}>{model==='cell'?'Compartments':'Regions'}</button>{model!=='cell'&&<button type="button" role="tab" aria-selected={hierarchy==='depth'} className={hierarchy==='depth'?'active':''} onClick={()=>setHierarchy('depth')}>Depth</button>}</div><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close anatomy browser"><X size={18}/></Button></div>
   {atlas&&(hierarchy==='depth'&&model!=='cell'?<DepthTree key={model} atlas={atlas} state={state} setState={setState} onChoose={choose}/>:<SystemTree key={model} atlas={atlas} mode={hierarchy==='depth'?'systems':hierarchy} state={state} setState={setState} onChoose={choose}/>)}
   {hierarchy!=='depth'&&(counts.integumentary>0||counts['cell-boundary']>0)&&<div className="skin-control"><label id="skin-label">{model==='cell'?'Cell membrane':'Skin / body surface'} <output>{state.visible.includes(model==='cell'?'cell-boundary':'integumentary')?Math.round((state.skinOpacity??.1)*100):0}%</output></label><Slider aria-labelledby="skin-label" min={0} max={100} step={5} value={[state.visible.includes(model==='cell'?'cell-boundary':'integumentary')?(state.skinOpacity??.1)*100:0]} onValueChange={v=>{const opacity=(Array.isArray(v)?v[0]:v)/100,surface=model==='cell'?'cell-boundary':'integumentary';setState(s=>({...s,skinOpacity:opacity,visible:opacity>0?[...s.visible.filter(x=>x!==surface),surface]:s.visible.filter(x=>x!==surface),depthHidden:opacity>0?s.depthHidden?.filter(x=>x!=='skin'):s.depthHidden}));}}/>{model!=='cell'&&<p>Outer surface reference; not separate skin layers.</p>}</div>}
  </section>}
  {panel==='search'&&show('search')&&<section className="search-panel glass" aria-label={model==='cell'?'Find cell component':'Find anatomy'}><div className="panel-heading"><span>Find a {model==='cell'?'component':'structure'}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><label className="check-label selection-mode"><input type="checkbox" checked={addSelection} onChange={e=>setAddSelection(e.target.checked)}/>Add to selection set</label><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={model==='cell'?'Nucleolus, mitochondria, Golgi apparatus…':'Heart, femur, cranial nerve…'} aria-label={model==='cell'?'Search named cell components':'Search named anatomical structures'} showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No {model==='cell'?'components':'structures'} match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':model==='cell'?'Search a component or organelle.':'Start with a major organ, or search every named structure.'}</p></section>}
  {show('camera')&&<nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.04&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false,camera:undefined}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>.04} aria-label={state.rotate?'Pause rotation':model==='cell'?'Rotate cell':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>}
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(currentChoice?.name??'SELECTED STRUCTURE'):state.explode>.95?(model==='cell'?'CELL COMPONENTS':'ANATOMICAL INVENTORY'):state.explode>.05?'SEPARATED STRUCTURES':model==='cell'?'HUMAN EUKARYOTIC CELL':model==='embryo'?'EMBRYO · ASSOCIATED TISSUES':sex==='female'?'FEMALE · REFERENCE ANATOMY':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  {show('explode')&&<div className="bottom-dock glass"><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode</label><output>{String(Math.round(state.explode*100)).padStart(2,'0')}%</output></div><div className="explode-slider-row"><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={(value,details)=>setExplosion(Array.isArray(value)?value[0]:value,details.reason==='drag'||details.reason==='track-press')} onValueCommitted={(value,details)=>{if(details.reason==='drag'||details.reason==='track-press')setExplosion(Array.isArray(value)?value[0]:value,true);}}/><div className="explode-ticks" aria-hidden="true">{Array.from({length:explodeSteps+1},(_,index)=><span key={index} style={{left:`${index/Math.max(1,explodeSteps)*100}%`}}/>)}</div></div></div></div>}
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the {model==='cell'?'cell':'anatomy'}</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'…'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  {show('details')&&<Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={open=>{if(open)setDetails(true);else clearSelection();}}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><SelectionInspector titleRef={detailTitle} choice={currentChoice} selectedParts={selectedParts} partById={parts} sex={sex} scope={atlas?.scope} state={state} covering={covering} depth={peelDepth} allowFadedSelection={allowFadedSelection} onOpacity={value=>setState(s=>({...s,contextOpacity:value/100}))} onDepth={setPeelDepth} onAllowFadedSelection={setAllowFadedSelection} onCenter={()=>setState(s=>({...s,focus:(s.focus??0)+1,camera:undefined}))} onIsolate={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))} onHide={hideSelection} onChoosePart={choosePart}/></SheetContent></Sheet>}
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">MODEL COVERAGE</div><SheetTitle className="structure-title">About this anatomy</SheetTitle><SheetDescription>Explore male and female reference models with different levels of detail.</SheetDescription><div className="about-copy"><p><strong>Male · detailed</strong><br/>Z-Anatomy mesh and curve anatomy, original Open 3D Model upper-limb structures, and selected missing digestive and pelvic structures from original BodyParts3D 4.0 geometry. Muscle attachments and fascia are hidden by default. The detailed and full-resolution menu options use the same geometry; the latter initially shows the outer surface.</p><p><strong>Male · standard</strong><br/>2,234 individual meshes and 3,432 named concepts built from BodyParts3D 4.0.</p><p><strong>Female anatomy</strong><br/>1,030 meshes and 1,234 named concepts built from original Human Reference Atlas v1.10 and v1.5 files plus 74 original University of Denver lower-limb muscle meshes aligned to HRA bones. The placenta and associated tissues are in the Embryo model. Upper-body muscle and bone coverage remains incomplete.</p><p>These models have different coverage. None contains every human structure or variation. Named concepts can contain multiple pieces; each mesh is rendered once.</p><p>Colors and system groupings are designed for exploration. Short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p></div></SheetContent></Sheet>
 </main>;
}
