import {structureName,type Atlas,type SceneState} from './anatomy';
import {REGIONS,REGION_NAMES,VIEWS} from './viewer-state';
import {Slider} from '@/components/ui/slider';
import {Button} from '@/components/ui/button';
interface Props{atlas:Atlas;state:SceneState;setState:(f:(s:SceneState)=>SceneState)=>void;close:()=>void;undo:()=>void;redo:()=>void;canUndo:boolean;canRedo:boolean;add:boolean;setAdd:(v:boolean)=>void;search:()=>void}
export default function StudyTools({atlas,state:s,setState,close,undo,redo,canUndo,canRedo,add,setAdd,search}:Props){
 const cell=atlas.scope==='cell';
 return <section className="study-panel glass" aria-label="Study tools"><div className="panel-heading">Study tools<Button variant="ghost" onClick={close} aria-label="Close study tools">×</Button></div><div className="study-scroll">
 <div className="study-history"><Button variant="outline" disabled={!canUndo} onClick={undo}>Undo</Button><Button variant="outline" disabled={!canRedo} onClick={redo}>Redo</Button></div>
 {!cell&&<><label>Region<select value={s.region??'all'} onChange={e=>setState(v=>({...v,region:e.target.value,reset:v.reset+1,camera:undefined}))}>{REGIONS.map((r,i)=><option value={r} key={r}>{REGION_NAMES[i]}</option>)}</select></label>{s.region&&s.region!=='all'&&<p>The whole-body surface is hidden in regional views.</p>}</>}<label>Point of view<select value={s.view} onChange={e=>setState(v=>({...v,view:e.target.value as SceneState['view'],reset:v.reset+1,camera:undefined}))}>{VIEWS.map(v=><option key={v} value={v}>{v==='side'?'Left':v==='right'?'Right':v==='superior'?'Above':v==='inferior'?'Below':v}</option>)}</select></label>
 <fieldset><legend>Selection set · {s.selected.length}</legend><label className="check-label"><input type="checkbox" checked={add} onChange={e=>setAdd(e.target.checked)}/>Add search results and clicks to this set</label><Button variant="outline" onClick={search}>Find and add {cell?'components':'anatomy'}</Button><label className="check-label"><input type="checkbox" checked={s.labels!==false} onChange={e=>setState(v=>({...v,labels:e.target.checked}))}/>Show labels on {cell?'components':'anatomy'}</label>
 <div className="selection-list">{s.selected.map(id=>{const p=atlas.parts.find(p=>p.id===id);return p&&<div key={id}><span>{structureName(p.name)}</span><button aria-label={`Remove ${structureName(p.name)} from selection`} onClick={()=>setState(v=>({...v,selected:v.selected.filter(x=>x!==id),isolate:v.selected.length>1&&v.isolate}))}>×</button></div>;})}</div>
 {s.selected.length>20&&<p>20 labels are displayed at a time. Remove items to label the rest.</p>}
 <Button variant="outline" disabled={!s.selected.length} onClick={()=>setState(v=>({...v,focus:(v.focus??0)+1,camera:undefined}))}>Focus selection</Button><Button variant="outline" disabled={!s.selected.length} onClick={()=>setState(v=>({...v,isolate:!v.isolate,explode:0}))}>{s.isolate?'Restore context':'Isolate selection set'}</Button>
 <Button variant="ghost" disabled={!s.selected.length} onClick={()=>setState(v=>({...v,hidden:[...new Set([...(v.hidden??[]),...v.selected])],selected:[],isolate:false}))}>Hide selected pieces</Button>
 <label id="context-label">Surrounding {cell?'components':'tissue'} opacity · {Math.round((s.contextOpacity??1)*100)}%</label><Slider aria-labelledby="context-label" disabled={!s.selected.length} value={[(s.contextOpacity??1)*100]} onValueChange={v=>setState(s=>({...s,isolate:false,contextOpacity:(Array.isArray(v)?v[0]:v)/100}))}/><p>Selected {cell?'components':'anatomy'} stay solid. Hidden layers stay hidden.</p></fieldset>
 </div></section>;
}
