import type {Atlas,SceneState} from './anatomy';
import {REGIONS,REGION_NAMES,VIEWS,PEEL_NAMES} from './viewer-state';
import {Slider} from '@/components/ui/slider';
import {Button} from '@/components/ui/button';
interface Props{atlas:Atlas;state:SceneState;setState:(f:(s:SceneState)=>SceneState)=>void;close:()=>void;undo:()=>void;redo:()=>void;canUndo:boolean;canRedo:boolean;add:boolean;setAdd:(v:boolean)=>void;search:()=>void}
export default function StudyTools({atlas,state:s,setState,close,undo,redo,canUndo,canRedo,add,setAdd,search}:Props){
 const section=s.section??{enabled:false,axis:'axial' as const,position:.5,flip:false};
 return <section className="study-panel glass" aria-label="Study tools"><div className="panel-heading">Study tools<Button variant="ghost" onClick={close} aria-label="Close study tools">×</Button></div><div className="study-scroll">
 <div className="study-history"><Button variant="outline" disabled={!canUndo} onClick={undo}>Undo</Button><Button variant="outline" disabled={!canRedo} onClick={redo}>Redo</Button></div>
 <label>Region<select value={s.region??'all'} onChange={e=>setState(v=>({...v,region:e.target.value,reset:v.reset+1,camera:undefined}))}>{REGIONS.map((r,i)=><option value={r} key={r}>{REGION_NAMES[i]}</option>)}</select></label>
 {s.region&&s.region!=='all'&&<p>The whole-body surface is hidden in regional views.</p>}<label>Point of view<select value={s.view} onChange={e=>setState(v=>({...v,view:e.target.value as SceneState['view'],reset:v.reset+1,camera:undefined}))}>{VIEWS.map(v=><option key={v} value={v}>{v==='side'?'Left':v==='right'?'Right':v==='superior'?'Above':v==='inferior'?'Below':v}</option>)}</select></label>
 <fieldset><legend>Selection set · {s.selected.length}</legend><label className="check-label"><input type="checkbox" checked={add} onChange={e=>setAdd(e.target.checked)}/>Add search results and clicks to this set</label><Button variant="outline" onClick={search}>Find and add anatomy</Button><label className="check-label"><input type="checkbox" checked={s.labels!==false} onChange={e=>setState(v=>({...v,labels:e.target.checked}))}/>Show labels on anatomy</label>
 <div className="selection-list">{s.selected.map(id=>{const p=atlas.parts.find(p=>p.id===id);return p&&<div key={id}><span>{p.name}</span><button aria-label={`Remove ${p.name} from selection`} onClick={()=>setState(v=>({...v,selected:v.selected.filter(x=>x!==id),isolate:v.selected.length>1&&v.isolate}))}>×</button></div>;})}</div>
 {s.selected.length>20&&<p>20 labels are displayed at a time. Remove items to label the rest.</p>}
 <Button variant="outline" disabled={!s.selected.length} onClick={()=>setState(v=>({...v,focus:(v.focus??0)+1,camera:undefined}))}>Focus selection</Button><Button variant="outline" disabled={!s.selected.length} onClick={()=>setState(v=>({...v,isolate:!v.isolate,explode:0}))}>{s.isolate?'Restore context':'Isolate selection set'}</Button>
 <Button variant="ghost" disabled={!s.selected.length} onClick={()=>setState(v=>({...v,hidden:[...new Set([...(v.hidden??[]),...v.selected])],selected:[],isolate:false}))}>Hide selected pieces</Button>
 <label id="context-label">Surrounding tissue opacity · {Math.round((s.contextOpacity??1)*100)}%</label><Slider aria-labelledby="context-label" disabled={!s.selected.length} value={[(s.contextOpacity??1)*100]} onValueChange={v=>setState(s=>({...s,isolate:false,contextOpacity:(Array.isArray(v)?v[0]:v)/100}))}/><p>Selected anatomy stays solid. Hidden layers stay hidden.</p></fieldset>
 <fieldset><legend>Peel tissue layers</legend><p>{PEEL_NAMES[s.peel??0]}</p><div className="study-history"><Button variant="outline" disabled={!s.peel} onClick={()=>setState(v=>({...v,peel:(v.peel??0)-1}))}>Restore layer</Button><Button variant="outline" disabled={(s.peel??0)>=7} onClick={()=>setState(v=>({...v,peel:(v.peel??0)+1}))}>Peel next layer</Button></div><p>System-based layers; selected pieces are retained.</p></fieldset>
 <fieldset><legend>Cross-section</legend><label className="check-label"><input type="checkbox" checked={section.enabled} onChange={e=>setState(v=>({...v,section:{...section,enabled:e.target.checked}}))}/>Enable cut</label><label>Plane<select value={section.axis} onChange={e=>setState(v=>({...v,section:{...section,axis:e.target.value as typeof section.axis}}))}><option value="axial">Axial · horizontal</option><option value="sagittal">Sagittal · left/right</option><option value="coronal">Coronal · front/back</option></select></label><label id="section-label">Cut position · {Math.round(section.position*100)}%</label><Slider aria-labelledby="section-label" disabled={!section.enabled} value={[section.position*100]} onValueChange={v=>setState(s=>({...s,section:{...section,position:(Array.isArray(v)?v[0]:v)/100}}))}/><label className="check-label"><input type="checkbox" checked={section.flip} onChange={e=>setState(v=>({...v,section:{...section,flip:e.target.checked}}))}/>Reverse retained side</label><p>Geometric cut, without filled tissue interiors. Not a scan.</p></fieldset>
 </div></section>;
}
